"""added tenants,houses and services

Revision ID: 56d6e833c68a
Revises: 9802987a2b63
Create Date: 2021-09-24 18:11:18.409889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d6e833c68a'
down_revision = '9802987a2b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_num', sa.String(length=5), nullable=True),
    sa.Column('locality', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_apt_num'), 'apartment', ['apt_num'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_num', sa.String(length=5), nullable=True),
    sa.Column('bhk', sa.String(length=3), nullable=True),
    sa.Column('rent', sa.String(length=4), nullable=True),
    sa.Column('advance', sa.String(length=4), nullable=True),
    sa.Column('vacancy', sa.Boolean(), nullable=False),
    sa.Column('apt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apt_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_advance'), 'house', ['advance'], unique=False)
    op.create_index(op.f('ix_house_bhk'), 'house', ['bhk'], unique=False)
    op.create_index(op.f('ix_house_house_num'), 'house', ['house_num'], unique=False)
    op.create_index(op.f('ix_house_rent'), 'house', ['rent'], unique=False)
    op.create_index(op.f('ix_house_vacancy'), 'house', ['vacancy'], unique=False)
    op.add_column('employee', sa.Column('dob', sa.DateTime(), nullable=False))
    op.add_column('employee', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('employee', sa.Column('service_id', sa.Integer(), nullable=True))
    op.drop_index('ix_employee_emer_num', table_name='employee')
    op.drop_index('ix_employee_services', table_name='employee')
    op.create_index(op.f('ix_employee_gender'), 'employee', ['gender'], unique=False)
    op.create_foreign_key(None, 'employee', 'service', ['service_id'], ['id'])
    op.drop_column('employee', 'services')
    op.add_column('tenant', sa.Column('mob_num', sa.String(length=10), nullable=True))
    op.add_column('tenant', sa.Column('dob', sa.DateTime(), nullable=False))
    op.add_column('tenant', sa.Column('Spouse_num', sa.String(length=10), nullable=True))
    op.add_column('tenant', sa.Column('house_id', sa.Integer(), nullable=True))
    op.drop_index('ix_tenant_email', table_name='tenant')
    op.drop_index('ix_tenant_mobile', table_name='tenant')
    op.drop_index('ix_tenant_services', table_name='tenant')
    op.create_index(op.f('ix_tenant_mob_num'), 'tenant', ['mob_num'], unique=True)
    op.create_unique_constraint(None, 'tenant', ['email'])
    op.create_foreign_key(None, 'tenant', 'house', ['house_id'], ['id'])
    op.drop_column('tenant', 'mobile')
    op.drop_column('tenant', 'services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('services', sa.VARCHAR(length=20), nullable=True))
    op.add_column('tenant', sa.Column('mobile', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_index(op.f('ix_tenant_mob_num'), table_name='tenant')
    op.create_index('ix_tenant_services', 'tenant', ['services'], unique=False)
    op.create_index('ix_tenant_mobile', 'tenant', ['mobile'], unique=False)
    op.create_index('ix_tenant_email', 'tenant', ['email'], unique=False)
    op.drop_column('tenant', 'house_id')
    op.drop_column('tenant', 'Spouse_num')
    op.drop_column('tenant', 'dob')
    op.drop_column('tenant', 'mob_num')
    op.add_column('employee', sa.Column('services', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_index(op.f('ix_employee_gender'), table_name='employee')
    op.create_index('ix_employee_services', 'employee', ['services'], unique=False)
    op.create_index('ix_employee_emer_num', 'employee', ['emer_num'], unique=False)
    op.drop_column('employee', 'service_id')
    op.drop_column('employee', 'gender')
    op.drop_column('employee', 'dob')
    op.drop_index(op.f('ix_house_vacancy'), table_name='house')
    op.drop_index(op.f('ix_house_rent'), table_name='house')
    op.drop_index(op.f('ix_house_house_num'), table_name='house')
    op.drop_index(op.f('ix_house_bhk'), table_name='house')
    op.drop_index(op.f('ix_house_advance'), table_name='house')
    op.drop_table('house')
    op.drop_table('service')
    op.drop_index(op.f('ix_apartment_apt_num'), table_name='apartment')
    op.drop_table('apartment')
    # ### end Alembic commands ###
