"""trying again

Revision ID: 6280a4eb8f89
Revises: 56d6e833c68a
Create Date: 2021-09-24 18:24:18.639871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6280a4eb8f89'
down_revision = '56d6e833c68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employee', 'service', ['service_id'], ['id'])
    op.drop_column('employee', 'name')
    op.drop_column('employee', 'services')
    op.add_column('tenant', sa.Column('mob_num', sa.String(length=10), nullable=True))
    op.add_column('tenant', sa.Column('dob', sa.DateTime(), nullable=False))
    op.add_column('tenant', sa.Column('Spouse_num', sa.String(length=10), nullable=True))
    op.add_column('tenant', sa.Column('house_id', sa.Integer(), nullable=True))
    op.drop_index('ix_tenant_email', table_name='tenant')
    op.drop_index('ix_tenant_mobile', table_name='tenant')
    op.drop_index('ix_tenant_services', table_name='tenant')
    op.create_index(op.f('ix_tenant_mob_num'), 'tenant', ['mob_num'], unique=True)
    op.create_unique_constraint(None, 'tenant', ['email'])
    op.create_foreign_key(None, 'tenant', 'house', ['house_id'], ['id'])
    op.drop_column('tenant', 'mobile')
    op.drop_column('tenant', 'services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('services', sa.VARCHAR(length=20), nullable=True))
    op.add_column('tenant', sa.Column('mobile', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_index(op.f('ix_tenant_mob_num'), table_name='tenant')
    op.create_index('ix_tenant_services', 'tenant', ['services'], unique=False)
    op.create_index('ix_tenant_mobile', 'tenant', ['mobile'], unique=False)
    op.create_index('ix_tenant_email', 'tenant', ['email'], unique=False)
    op.drop_column('tenant', 'house_id')
    op.drop_column('tenant', 'Spouse_num')
    op.drop_column('tenant', 'dob')
    op.drop_column('tenant', 'mob_num')
    op.add_column('employee', sa.Column('services', sa.VARCHAR(length=20), nullable=True))
    op.add_column('employee', sa.Column('name', sa.VARCHAR(length=40), nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    # ### end Alembic commands ###
