"""removed dynamic loaders

Revision ID: 9802987a2b63
Revises: c8f4af51e351
Create Date: 2021-09-24 14:20:38.233984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9802987a2b63'
down_revision = 'c8f4af51e351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=True),
    sa.Column('lname', sa.String(length=25), nullable=True),
    sa.Column('mobile', sa.String(length=10), nullable=True),
    sa.Column('emer_num', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('services', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_email'), 'tenant', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_emer_num'), 'tenant', ['emer_num'], unique=False)
    op.create_index(op.f('ix_tenant_fname'), 'tenant', ['fname'], unique=False)
    op.create_index(op.f('ix_tenant_lname'), 'tenant', ['lname'], unique=False)
    op.create_index(op.f('ix_tenant_mobile'), 'tenant', ['mobile'], unique=True)
    op.create_index(op.f('ix_tenant_services'), 'tenant', ['services'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_services'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_mobile'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_lname'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_fname'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_emer_num'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_email'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
