"""empty message

Revision ID: bf688a378807
Revises: 8784ea44f505
Create Date: 2021-10-09 19:38:38.646957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf688a378807'
down_revision = '8784ea44f505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('dot', sa.DateTime(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('ten_id', sa.Integer(), nullable=True),
    sa.Column('amt', sa.String(length=4), nullable=True),
    sa.Column('desc', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['ten_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
