"""Added attributes to employee table

Revision ID: c8f4af51e351
Revises: e53fd707bde1
Create Date: 2021-09-24 14:08:42.675284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f4af51e351'
down_revision = 'e53fd707bde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('fname', sa.String(length=25), nullable=True))
    op.add_column('employee', sa.Column('lname', sa.String(length=25), nullable=True))
    op.add_column('employee', sa.Column('emer_num', sa.String(length=10), nullable=True))
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('employee', sa.Column('services', sa.String(length=20), nullable=True))
    op.drop_index('ix_employee_name', table_name='employee')
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_emer_num'), 'employee', ['emer_num'], unique=False)
    op.create_index(op.f('ix_employee_fname'), 'employee', ['fname'], unique=False)
    op.create_index(op.f('ix_employee_lname'), 'employee', ['lname'], unique=False)
    op.create_index(op.f('ix_employee_services'), 'employee', ['services'], unique=False)
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.VARCHAR(length=40), nullable=True))
    op.drop_index(op.f('ix_employee_services'), table_name='employee')
    op.drop_index(op.f('ix_employee_lname'), table_name='employee')
    op.drop_index(op.f('ix_employee_fname'), table_name='employee')
    op.drop_index(op.f('ix_employee_emer_num'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.create_index('ix_employee_name', 'employee', ['name'], unique=False)
    op.drop_column('employee', 'services')
    op.drop_column('employee', 'email')
    op.drop_column('employee', 'emer_num')
    op.drop_column('employee', 'lname')
    op.drop_column('employee', 'fname')
    # ### end Alembic commands ###
